(function(){(function(){var n={},l,a,t,f,p,u,w,x;n.CFG={IDS:{btnPrev:"Previous",btnNext:"Next",moreInAdv:"none",noneMoreInAdv:"none",notFound:"none"},scheme:{nodeCtn:null,nodeMainHeader:null,nodeMainFooter:null,nodeMainData:null,nodeListCtn:null,nodeListLine:null,nodeListItem:null,nodeItemBlock:null,nodeItemData:null,nodeFooterBtn:null},styleCSS:null,keyCodeMove:{37:"left",38:"up",39:"right",40:"down"},keyCodeEnter:13,dataCfg:{ccode:null,showSMImg:1},showDataCfg:{baseUrl:null,searchUrl:null,lang:0,
currPage:1,currSelectedIdx:null,currSelectedId:0,maxPageLen:3,maxByPage:9,maxByLine:3,maxByCol:3,cssMaxWidth:750,cssMaxHeight:0,rplCanonicalUrl:null,pathImg:null,oriInputValue:"",fieldList:["Price","SMImg","Name","ItemSKU","CanonicalURL"],
fieldRplList:[{field:"Price",dataRplScr:"#DATA_SRC#",dataRplHtml:""}],
fieldImgList:"[SMImg]",tagImgRplSrc:"#IMG-SRC#",tagImgRplHtml:null},js:{urlTT:null},tagSearch:null,idCSSNode:"OxTTCSSInserted",node:{searchForm:null,searchInput:null,searchInputOri:null,mainListItem:null},
ws:{url:"ws/wsSearch.asp",action:{searchText:1,config:2}},tempoKeyStroke:{setTimeout:null,timer:350},mouse:{isHoverTT:!1},search:{text:null,charMin:1,data:null,dataLen:null,pageIdx:null},m_bInitNeeded:!0,m_bInitDocLoaded:!1,m_bInitCfgLoaded:!1,m_bInitTerminated:!1,m_oTT:null,m_sTTPos:"",m_nTTLeft:0,m_bWSRunning:!1,m_bJSLoaded:!1,m_bHideButton:!1,m_bKeyNav:!1,m_bUseExtCfg:!1,m_bExternalFunctionEnable:!1,m_bShowPrice:!1,m_vTestVersion:1,m_bFormFound:!1};n.EVENTS={setInput:function(){var b=!1;a.node.searchInput&&
(f.nodeAttrs(a.node.searchInput,{autocomplete:"off"}),a.node.searchInput.onfocus="",f.nodeEvent(a.node.searchInput,{focus:function(b){w.inputFocused(b)}},!0,!0,!0),f.nodeEvent(a.node.searchInput,{keyup:function(b){w.tempoKey(b)}},!0),f.nodeEvent(a.node.searchInput,{blur:function(b){w.loseFocus(b)}},!0),f.nodeEvent(a.node.searchInput,{click:function(b){l.setInputValue(!0)}},!0),b=!0);return b},tempoKey:function(b){var c=b.keyCode||null,d;b=!0;if(a.m_bKeyNav)if(c==a.keyCodeEnter)a.showDataCfg.currSelectedId?
(d=f.getNodeById("IdOxSearchPanelItem-"+a.showDataCfg.currSelectedId))&&d.click():(a.node.searchInputOri.value=window.OXRTSInputDefaultText||a.node.searchInput.value,a.node.searchForm.submit());else if(d=a.keyCodeMove[c])l.changeSelectedItem({changeTo:d}),b=!1;b&&(a.tempoKeyStroke.setTimeout&&clearTimeout(a.tempoKeyStroke.setTimeout),a.tempoKeyStroke.setTimeout=setTimeout(function(){l.setInputValue()},a.tempoKeyStroke.timer))},inputFocused:function(b){(a.node.searchInput.value||"")==(a.showDataCfg.oriInputValue||
"")&&(a.node.searchInput.value="")},loseFocus:function(){var b=a.node.searchInput.value||"",c=a.showDataCfg.oriInputValue||"";if(/[\&\?]dbgmodejs\=1/i.test(window.location.href||"?"))return!1;a.m_oTT&&!a.mouse.isHoverTT&&p.hide();b||(a.node.searchInput.value=c)}};n.TTIPS={m_nItemShown:0,m_ndContent:null,hide:function(){p.m_nItemShown=0;p.m_ndContent=null;a.m_oTT&&a.m_oTT.remove()},show:function(b){b=b||{};var c,d;c=b.html||"??";b=!0;a.m_oTT&&p.m_ndContent&&p.m_nItemShown&&3<=p.m_nItemShown&&3<=a.search.data.length&&
(b=!1);b?(b={nodeLink:a.node.searchInput,html:c,position:a.m_sTTPos,positionAutoDisable:!0,left:a.m_nTTLeft,arrow:"none",cssBorderWidth:"1px",cssBorderRadius:"2px",cssMaxWidth:a.showDataCfg.cssMaxWidth,cssMaxHeight:a.showDataCfg.cssMaxHeight,cssPaddingContent:2,show:!0,hidden:!0,success:function(b){var c,d;p.m_ndContent=b.node.content;p.m_nItemShown=a.search.data.length;if(c=f.getNodeById("maincontainer"))d=f.nodeMetrics(c),c=f.nodeMetrics(b.node.root),0>(d=d.left+d.width-c.left-c.width)&&(b.node.root.style.left=
c.left+d+"px"),b.node.main.style.visibility="visible"}},"undefined"!=typeof COXTooltipsHelper&&(a.m_oTT=new COXTooltipsHelper(b)),a.m_oTT||"undefined"==typeof CADTooltipsHelper||(a.m_oTT=new CADTooltipsHelper(b)),a.m_oTT&&(d=a.m_oTT.CFG.node.main)&&(f.nodeEvent(d,{mouseover:function(){a.mouse.isHoverTT=!0}},!0,!0,!0),f.nodeEvent(d,{mouseout:function(){a.mouse.isHoverTT=!1}},!0,!0,!0),f.nodeCSS(a.m_oTT.CFG.node.root,{width:"auto",height:"auto"}))):(p.m_ndContent.innerHTML="",f.isObjNotEmpty(c)&&(c=
f.nodeCreate(c)),f.isNode(c)&&p.m_ndContent.appendChild(c),"string"==typeof c&&(p.m_ndContent.innerHTML=c))}};n.VALID={valSearchText:function(){var b=a.search.text;return b="string"==typeof b&&b.length>=a.search.charMin?b:!1},searchCCode:function(){var b,c=null,d,e,f;f=null;var h=['input[name="CCode"]'],m=1,g=null;b=!1;if(e=(window.strStatParams||"?").match(/(^|[^a-z])ccode=(2|6)([^\d]|$)/i))3<=e.length&&(c=e[2]),c&&(b=!0);if(!b&&(g=a.node.searchInput.name,(d=document.getElementsByTagName("form"))&&
d.length)){e=null;m=2;for(g&&(m=1);2>=m;m++){e=null;for(var r=0,v=d.length;r<v&&(e=d[r],f=e.name,/(^|\/)pbsearch.asp(\?|\#|$)/i.test(e.action)?1==m&&(f=new RegExp("^"+f),f.test(g)||(e=null)):e=null,!e);r++);if(e)break}if(e)for(g=0,m=h.length;g<m&&(sQrySel=h[g],(d=e.querySelectorAll(sQrySel))&&d.length&&(c=d[0].value)&&(b=!0),!b);g++);}return c}};n.RENDER={initSearchBlock:function(){var b,c,d=a.tagSearch||null;b=!1;f.isObjNotEmpty(d)?c=[d]:f.isArray(d)&&(c=d);if(f.isArray(c)){b=!1;for(var e=0,q=c.length;e<
q;e++)if(a.node.searchInputOri=f.getNode(c[e].input),f.isNode(a.node.searchInputOri)&&/^text$/i.test(a.node.searchInputOri.type||"")&&f.isVisible(a.node.searchInputOri)&&(d=a.node.searchInputOri.getAttribute("data-input"),!/^pbsearch-search$/i.test(d))){b=!0;break}b?(a.m_bFormFound=/^form$/i.test(a.node.searchInputOri.parentNode.tagName),a.m_bKeyNav=!1,window.OXRTSInputDefaultText&&(a.node.searchInputOri.value=window.OXRTSInputDefaultText),a.showDataCfg.oriInputValue=a.node.searchInputOri.value||
"",a.node.searchInput=a.node.searchInputOri):(a.node.searchInput=null,a.node.searchInputOri=null)}return b},renderHeader:function(b){return b},renderFooter:function(b){b=b||{};var c,d,e,q,h=a.search.data.length,m=0;if(f.isNode(b.nodeContainer)){c=f.nodeCreate(a.scheme.nodeMainFooter);1==a.m_vTestVersion&&c.appendChild(f.nodeCreate({"class":"OxSearchPanelBlkAdv itemsFound",html:{tag:"a","class":"PBMainTxt OxSearchPanelNavBtn OxSchPnlAdvBtn",html:f.nodeCreate({html:a.IDS.moreInAdv}),event:{click:function(){window.location.assign(a.showDataCfg.searchUrl.replace(/\#SEARCH\#/g,
a.node.searchInput.value||""))}}}}));d=f.nodeCreate({"class":"OxSearchPanelBlkNavBtn"});q=1<a.showDataCfg.currPage;h=a.showDataCfg.currPage*a.showDataCfg.maxByPage<h;if(q||h)e=f.nodeCreate(a.scheme.nodeFooterBtn),f.nodeEvent(e,{click:function(b){l.pagePrevious(b)}},!0,!0,!0),f.nodeToggleClass(e,"PBMainTxt OxSearchPanelNavBtn OxSchPnlPrevious"+(q?"":" OxSearchPanelBtnHide"),!0),e.appendChild(f.nodeCreate({html:"<<&nbsp;"+a.IDS.btnPrev})),d.appendChild(e),m++,q=f.nodeCreate(a.scheme.nodeFooterBtn),
f.nodeEvent(q,{click:function(b){l.pageNext(b)}},!0,!0,!0),f.nodeToggleClass(q,"PBMainTxt OxSearchPanelNavBtn OxSchPnlNext"+(h?"":" OxSearchPanelBtnHide"),!0),q.appendChild(f.nodeCreate({html:a.IDS.btnNext+"&nbsp;>>"})),d.appendChild(q),m++;m&&(d.appendChild(f.nodeCreate({tag:"br",css:{clear:"both"}})),c.appendChild(d));c.appendChild(f.nodeCreate({tag:"br",css:{clear:"both"}}));b.nodeContainer.appendChild(c)}},addNodeToSchemeByKey:function(b,a,d){if(f.isArray(b))for(var e=0,q=b.length;e<q;e++)t.addNodeToSchemeByKey(b[e],
a,d);else if(f.isObj(b))for(e in b)b[e]&&("appendKeys"==e&&0<=b[e].indexOf("["+a+"]")?(b.html?b.html.push(d):b.html=[d],b[e]=b[e].replace("["+a+"]",""),b[e]||delete b[e]):"html"==e.toLowerCase()&&t.addNodeToSchemeByKey(b[e],a,d));return b},buildHtmlItems:function(b){b=b||{};var c,d,e,q,h,m,g,r,v,n,l;g=a.showDataCfg.maxByPage;r=a.showDataCfg.maxByLine;d=a.showDataCfg.currPage;q=f.nodeCreate(a.scheme.nodeListCtn);c=g*(d-1);d*=g;if(c+1<=a.search.data.length){h=f.nodeCreate(f.objClone(a.scheme.nodeListItem));
for(var p=c;p<d;p++)if(l="",m=a.search.data[p]||null)if(f.nodeCreate(a.scheme.nodeListItem),c=f.objClone(a.scheme.nodeItemBlock),b.nodeContainer&&m.ID){c.id="IdOxSearchPanelItem-"+m.ID;v=(e=m.CanonicalURL||a.showDataCfg.baseUrl+m.ID||null)?!0:!1;if(n=m.SMImg)n=a.showDataCfg.pathImg+"/"+m.SMImg,a.showDataCfg.tagImgRplHtml&&(n=a.showDataCfg.tagImgRplHtml.replace("#IMG-SRC#",n));c.html[0].html=n||"";c.html[1].html[0].html=m.Name||"";c.html[1].html[1].html.html=a.m_bShowPrice?m.Price:"";c.attrs=c.attrs||
{};c.attrs["data-pdt-id"]=m.ID;c.attrs["data-pdt-parent-id"]=m.ParentID||"";c.attrs["data-pdt-type"]=0===m.Type?"0":m.Type||"";c.attrs["data-url"]=e||"";c.attrs.onclick="window.location.assign(this.getAttribute('data-url'));";e=p%g+1;e<=r&&(l+=" OxLineFirst");e>g-r&&(l+=" OxLineLast");e=(e-1)%r+1;1==e&&(l+=" OxColumnFirst");e>=a.showDataCfg.maxByCol&&(l+=" OxColumnLast");l&&(c["class"]+=l);v&&h.appendChild(f.nodeCreate(c))}b.nodeContainer.appendChild(h)}return q},showResult:function(b){b=b||{};var c,d,e=b.data||{},q=e.result?!0:!1,h=!1;b.keepSelectedItem||
l.initSelectedItem();if(q||b.refresh)e.IsCCodeSet&&(a.dataCfg.ccode=e.CCode),a.showDataCfg.lang=e.Lang||0,a.showDataCfg.pathImg=e.SMImgPath||a.showDataCfg.pathImg,a.showDataCfg.baseUrl=e.BaseUrl||a.showDataCfg.baseUrl,a.showDataCfg.searchUrl=e.SearchUrl||a.showDataCfg.searchUrl,a.IDS.btnPrev=e.IDSBtnPrev||a.IDS.btnPrev,a.IDS.btnNext=e.IDSBtnNext||a.IDS.btnNext,a.IDS.moreInAdv=e.IDSMoreInAdv||a.IDS.moreInAdv,a.IDS.noneMoreInAdv=e.IDSNoneMoreInAdv||a.IDS.noneMoreInAdv,a.IDS.notFound=e.IDSNotFound||
a.IDS.notFound,a.m_bShowPrice="undefined"==typeof e.ShowPrice?a.m_bShowPrice:e.ShowPrice?!0:!1,b.refresh||(a.search.dataLen=e.recordCount,a.search.data=e.data||[]),a.search.data.length&&(c=f.nodeCreate(a.scheme.nodeCtn),c=t.renderHeader(c),a.scheme.nodeMainData&&(d=f.nodeCreate(a.scheme.nodeMainData))&&c.appendChild(d),d=d||c,t.buildHtmlItems({nodeContainer:d}),t.renderFooter({nodeContainer:d}),h=!0),c||(c=1==a.m_vTestVersion?f.nodeCreate({"class":"OxSearchPanelBlkAdv noItemsFound",html:[{tag:"span",
"class":"PBMainTxt OxSchPnlText",html:a.IDS.notFound},{tag:"a","class":"PBMainTxt OxSearchPanelNavBtn OxSchPnlAdvBtn",html:f.nodeCreate({tag:"span",html:a.IDS.noneMoreInAdv}),event:{click:function(){window.location.assign(a.showDataCfg.searchUrl.replace(/\#SEARCH\#/g,a.node.searchInput.value||""))}}}]}):f.nodeCreate({tag:"font","class":"PBMsg",html:a.IDS.notFound})),!h&&c&&(h=!0),h?(p.show({html:c}),f.isFct(b.fctNext)&&b.fctNext()):p.hide()},setStyleCSS:function(){f.nodeRemove(f.getNodeById(a.idCSSNode));
document.getElementsByTagName("head")[0].appendChild(f.nodeCreate({tag:"style",id:a.idCSSNode,attrs:{type:"text/css"},html:a.styleCSS}))}};n.WS={setStatus:function(b){a.m_bWSRunning=b?!0:!1},isRunning:function(){return a.m_bWSRunning?!0:!1},getConfig:function(b){if(b||!a.m_bInitCfgLoaded)if(a.m_bInitCfgLoaded=!0,a.m_bUseExtCfg){if(u.isRunning())return!1;u.setStatus(!0);f.ajax({post:!0,async:!0,json:!0,url:a.ws.url,data:{action:a.ws.action.config},success:function(b){u.setStatus(!1);l.setConfig({data:b})}})}else l.setConfig({data:null})},
searchText:function(){var b;if(!1===x.valSearchText())return p.hide(),!1;if(u.isRunning())return!1;u.setStatus(!0);b={action:a.ws.action.searchText,search:a.search.text};a.dataCfg.ccode||(a.dataCfg.ccode=x.searchCCode());a.dataCfg.ccode&&(b.CCode=a.dataCfg.ccode);f.ajax({post:!0,async:!0,json:!0,url:a.ws.url,data:b,success:function(b){if(-1!=b.result){var d=!1;u.setStatus(!1);a.showDataCfg.currPage=1;a.m_bExternalFunctionEnable&&"function"==typeof RealTimeSearchExternal&&(d=RealTimeSearchExternal({data:b}));
d||t.showResult({data:b})}}})}};n.ACTION={initSelectedItem:function(){a.showDataCfg.currSelectedId=0;a.showDataCfg.currSelectedIdx=null;l.showSelectedItem()},setConfig:function(b){var c;if(b&&(c=b.data)&&c.result){if(a.dataCfg.ccode=c.CCode,a.js.urlTT=c.PathJSFileTooltips||a.js.urlTT,a.styleCSS=c.CSS||a.styleCSS,a.showDataCfg.lang=c.Lang||a.showDataCfg.lang,a.showDataCfg.rplCanonicalUrl=c.RplCanonicalURL||a.showDataCfg.rplCanonicalUrl,a.showDataCfg.pathImg=c.PathImage||a.showDataCfg.pathImg,a.tempoKeyStroke.timer=
c.KeystrokeTimeout||a.tempoKeyStroke.timer,a.showDataCfg.maxPageLen=c.MaxPageLen||a.showDataCfg.maxPageLen,a.showDataCfg.maxByLine=c.MaxByLine||a.showDataCfg.maxByLine,a.showDataCfg.maxByCol=c.MaxByCol||a.showDataCfg.maxByCol,a.showDataCfg.maxByPage=a.showDataCfg.maxByLine*a.showDataCfg.maxByCol||a.showDataCfg.maxByPage,a.search.charMin=0<=c.CharMin?c.CharMin:a.search.charMin,a.scheme.nodeListCtn=f.getJSON(c.SchmNodeListCtn)||a.scheme.nodeListCtn,a.scheme.nodeListLine=f.getJSON(c.SchmNodeListLine)||
a.scheme.nodeListLine,a.scheme.nodeListItem=f.getJSON(c.SchmNodeListItem)||a.scheme.nodeListItem,a.scheme.nodeItemBlock=f.getJSON(c.SchmNodeItemBlock)||a.scheme.nodeItemBlock,a.scheme.nodeCtn=f.getJSON(c.SchmCtn)||a.scheme.nodeCtn,a.scheme.nodeMainHeader=f.getJSON(c.SchmMainHeader)||a.scheme.nodeMainHeader,a.scheme.nodeMainFooter=f.getJSON(c.SchmMainFooter)||a.scheme.nodeMainFooter,a.scheme.nodeMainData=f.getJSON(c.SchmMainData)||a.scheme.nodeMainData,a.scheme.nodeItemData=f.getJSON(c.SchmItemData)||
a.scheme.nodeItemData,a.scheme.nodeFooterBtn=f.getJSON(c.SchmFooterBtn)||a.scheme.nodeFooterBtn,a.showDataCfg.fieldRplList=c.FieldRplList||a.showDataCfg.fieldRplList,a.showDataCfg.tagImgRplHtml=c.TagImgRplHtml||a.showDataCfg.tagImgRplHtml,b=f.getJSON(c.TagSearch)||a.tagSearch)b.tgSchCfg&&(b=b.tgSchCfg),a.tagSearch=b}else a.js.urlTT="Javascript/oxtooltipshelper.js",a.scheme.nodeCtn={id:"OxSearchPanel","class":"sectiondata"},a.scheme.nodeMainData={"class":"sectiondataarea"},a.scheme.nodeListItem={id:"OxSearchAnswers"},
a.scheme.nodeMainFooter={"class":"OxSearchPanelNavBar"},a.scheme.nodeItemBlock={"class":"OxSearchPanelDataLink",html:[{"class":"PBItemImg",html:"[SMImg]"},

{"class":"PBItemInfos",html:[{"class":"PBShortTxt",html:"[Name]"},
{"class":"PBItemPrice",html:{tag:"span","class":"PBCurrency",html:"[Price]"}},

{"class":"PBItemSku",html:{"class":"PBShortTxt",html:"[ItemSKU]"}},


 ]}]},a.scheme.nodeFooterBtn={tag:"a","class":"OxSearchPanelBtn"},a.showDataCfg.tagImgRplHtml='<img src="#IMG-SRC#" class="smallImg" />',a.tagSearch=[{input:{id:null,name:"SearchText"},button:{id:null,"class":"blockbtn"}},
{input:{id:null,name:"searchformtext"},button:{id:null,name:"searchformBtn"}}],a.styleCSS=" #OxSearchPanel { margin: 0px; padding: 0px; border: none; background-color: #fff; font-size: 12px; text-align: left;} #OxSearchPanel .sectiondataarea { padding: 1em; } #OxSearchAnswers { width: 60em; min-height: 27.5em; }  .OxSearchPanelDataLink { display: inline-block; width: 18em; border:1px solid #ebebeb; min-height:7em; vertical-align: top; margin:0 0 1em 1em; padding: 0.5em; }  .OxSearchPanelDataLink:hover { cursor: pointer;  box-shadow: 1px 1px 1em 1px #656565; } .OxSearchPanelItemSelected { box-shadow: 1px 1px 1em 1px #656565; } .OxSearchPanelDataLink:nth-of-type(3n+1) { margin-left: 0; } .OxSearchPanelDataLink .PBItemInfos .PBShortTxt { font-size: 1em; line-height: 1.2em; } .OxSearchPanelDataLink .PBItemInfos .PBCurrency { font-size: 1.2em; line-height: 1.5em; } .OxSearchPanelDataLink .PBItemInfos , .OxSearchPanelLink .PBItemImg { display: block; vertical-align: top; } .OxSearchPanelDataLink .PBItemImg { margin-left:1em; float:right; } .OxSearchPanelDataLink .PBItemImg img { max-height: 6em; max-width: 6em; } .OxSearchPanelNavBar { text-align: right; } .OxSearchPanelNavBar .OxSearchPanelBtnHide { visibility: hidden; } .OxSearchPanelNavBtn { display:inline-block; \t/*height: 20px;*/padding: 5px 10px; background-color:#F4F4F4; \tcolor: #666;/* font-weight:normal;font-size: 14px;font-family : arial, sans-serif;*/ \tborder: 1px solid #D0D0D0;\tcursor: pointer;} .OxSearchPanelNavBtn.OxSchPnlNext { margin-left: 10px; } .OxSearchPanelBlkAdv .OxSchPnlAdvBtn:hover { /*background-image: url('/Files/0//icon-search-white-20X20.png');*/ } .OxSearchPanelBlkAdv.noItemsFound { margin: 10px; } .OxSearchPanelBlkAdv.noItemsFound span, .OxSearchPanelBlkAdv.noItemsFound a { margin: 2px 10px; } .OxSearchPanelBlkAdv span, .OxSearchPanelBlkAdv a { display: inline-block; margin: 2px 10px; line-height: 20px; } .OxSearchPanelBlkAdv .OxSchPnlAdvBtn { padding-left: 35px; \tbackground: url('/Files/0//icon-search-black-20X20.png') 7px center no-repeat #F4F4F4; } .OxSearchPanelBlkAdv.itemsFound .OxSchPnlAdvBtn { margin: 0px; } .OxSearchPanelNavBar .OxSearchPanelBlkAdv, .OxSearchPanelNavBar .OxSearchPanelBlkNavBtn  { display: inline-block; float: left; } .OxSearchPanelNavBar .OxSearchPanelBlkNavBtn  { float: right; }"},
setTTCfg:function(){var b,c,d;if(!f.isNode(a.node.searchInput))return!1;b=f.docMetrics();c=f.nodeMetrics(a.node.searchInput);b=parseInt(b.width/2,10);nDocWHlf=10;d=c.right;c=Math.abs(parseInt((c.left+c.right)/2));a.m_sTTPos=d>=b+c?"bottom-right":"bottom-left"},setInputValue:function(b){var c=a.node.searchInput,c=c.value?c.value:null;b=b?!0:!1;c=(c||"").replace(/\s+/g," ").replace(/(^\s+|\s+$)/g,"");if(b||c!=a.search.text)a.search.text=c,u.searchText()},showSelectedItem:function(){var b=a.search.data||
null,c=a.showDataCfg.currSelectedId||0,d=a.showDataCfg.currPage;if(!b)return!1;for(var e=(d-1)*a.showDataCfg.maxByPage,q=d*a.showDataCfg.maxByPage-1;e<=q;e++)if(d=(oDI=b[e])?oDI.ID:0)ndT=f.getNodeById("IdOxSearchPanelItem-"+d),f.nodeToggleClass(ndT,"OxSearchPanelItemSelected",c==d)},changeSelectedItem:function(b){b=b||{};b=(b.changeTo||"?").toLowerCase();var c,d,e=a.search.data||null,q=e.length||0,h=a.showDataCfg.currPage,m=a.showDataCfg.currSelectedId,g=a.showDataCfg.currSelectedIdx,r,v;c=r=!1;if(!q)return!1;
a.m_oTT&&a.m_oTT.CFG&&a.m_oTT.CFG.node&&(c=f.isVisible(a.m_oTT.CFG.node.root));if(!c)return!1;c=Math.floor(g/a.showDataCfg.maxByPage)+1;bPageFirst=1>=c;v=c>=a.showDataCfg.maxPageLen;if("left"==b)if(g)if(g<=(h-1)*a.showDataCfg.maxByPage){if(bPageFirst)return l.initSelectedItem(),a.node.searchInput.focus(),!0;h=c-1;g--;r=!0}else g--;else return l.initSelectedItem(),a.node.searchInput.focus(),!0;else if("up"==b)if(g)if(g<=(h-1)*a.showDataCfg.maxByPage){if(bPageFirst)return l.initSelectedItem(),a.node.searchInput.focus(),
!0;h=c-1;g--;r=!0}else g--;else return l.initSelectedItem(),a.node.searchInput.focus(),!0;else"right"==b?null===g?g=h-1:g>=q-1?(h=1,g=0,r=h!=c):g>=h*a.showDataCfg.maxByPage-1?(v?(h=1,g=0):(h=c+1,g++),r=!0):g++:"down"==b&&(null===g?g=h-1:g>=q-1?(h=1,g=0,r=h!=c):g>=h*a.showDataCfg.maxByPage-1?(v?(h=1,g=0):(h=c+1,g++),r=!0):g++);null!=g&&(m=(d=e[g])?d.ID:0);a.showDataCfg.currPage=h;a.showDataCfg.currSelectedId=m;a.showDataCfg.currSelectedIdx=g;r?t.showResult({refresh:!0,keepSelectedItem:!0,fctNext:function(){l.showSelectedItem()}}):
l.showSelectedItem()},pageChange:function(){l.initSelectedItem();t.showResult({refresh:!0})},pagePrevious:function(b){1<a.showDataCfg.currPage&&(a.showDataCfg.currPage--,l.pageChange())},pageNext:function(b){a.showDataCfg.currPage*a.showDataCfg.maxByPage<a.search.data.length&&(a.showDataCfg.currPage++,l.pageChange())}};n.init=function(b){b=b||{};var c=!1;if(a.m_bInitTerminated||a.m_bInitDocLoaded&&a.m_bJSLoaded)return!0;b.docLoaded&&(a.m_bInitDocLoaded=!0);b.jsTTLoaded&&(a.m_bJSLoaded=!0);if(a.m_bInitNeeded){u.getConfig();
c=t.initSearchBlock();if(!c)return!1;a.m_bInitNeeded=!1}if(!a.js.urlTT)return!1;if(a.m_bJSLoaded||"function"==typeof COXTooltipsHelper||"function"==typeof CADTooltipsHelper){c=w.setInput();if(!c)return!1;l.setTTCfg();t.setStyleCSS();a.m_bInitTerminated=!0;if(b=(window.location.href||"?").match(/[\&\?\/]testversion\=(\d+)/i))a.m_vTestVersion=b&&2==b.length?b[1]:a.m_vTestVersion}else document.getElementsByTagName("HEAD")[0].appendChild(f.nodeCreate({tag:"script",event:{onload:function(b){n.init({jsTTLoaded:1})}},
attrs:{type:"text/javascript",src:a.js.urlTT}}))};n.TOOLS={isNull:function(b){return null===b},isNu:function(b){return"number"==typeof b},isFct:function(b){return"function"==typeof b},isNode:function(b){return b&&1==b.nodeType},isArray:function(b){return"object"==typeof b&&!this.isNull(b)&&0<=b.length},isObj:function(b){return"object"==typeof b&&!this.isNull(b)&&"undefined"==typeof b.length},isObjNotEmpty:function(b){if(!this.isObj(b))return!1;var a=!1;for(k in b)if(b[k]){a=!0;break}return a},isVisible:function(b){return this.isNode(b)&&
this.nodeMetrics(b).width?!0:!1},objClone:function(b){var a={};if(this.isObj(b)){for(var d in b)a[d]=this.objClone(b[d]);return a}if(this.isArray(b)){a=[];d=0;for(var e=b.length;d<e;d++)a[d]=this.objClone(b[d]);return a}return b},nodeAttrs:function(b,a){if(!this.isNode(b)||!this.isObjNotEmpty(a))return!1;for(var d in a)b.setAttribute(d.toLowerCase(),a[d]);return b},nodeUnbind:function(b,a,d){if(!this.isNode(b)||!(a=a.toLowerCase().replace(/^(on)/,"")))return!1;if(d=(this.nodeEventListenerList||{})[a]){b[a]=
null;for(var e=0,f=d.length;e<f;e++)document.removeEventListener?b.removeEventListener(a,d[e][0],d[e][1]):b.detachEvent&&b.detachEvent("on"+a,d[e][0]);this.nodeEventListenerList[a]=[]}},nodeBind:function(b,a,d,e,f){if(!this.isNode(b)||!this.isObjNotEmpty(a))return!1;var h,m,g;f=f?!0:!1;for(var l in a)if("function"==typeof a[l]||e)h=d?function(b){b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;return a[l](b,b.target||b.srcElement||null)}:function(b){return a[l](b,b.target||b.srcElement||null)},
m=l.toLowerCase().replace(/^(on)/,""),e&&this.nodeUnbind(b,m),this.nodeEventListenerList=this.nodeEventListenerList||{},g=this.nodeEventListenerList[m]||[],g.push([h,f]),this.nodeEventListenerList[m]=g,document.addEventListener?b.addEventListener(m,h,f):b.attachEvent&&b.attachEvent("on"+m,h);return b},nodeEvent:function(b,a,d,e,f){return this.nodeBind(b,a,d,e,f)},nodeCSS:function(b,a){if(!this.isNode(b)||!this.isObjNotEmpty(a))return!1;var d,e;for(d in a)e=d.toLowerCase().replace(/-[a-z]/gi,function(b){return b.substr(-1).toUpperCase()}),
b.style[e]=a[d]},nodeCreate:function(b){b=b||{};var a=document.createElement(b.tag||"div");b.id&&(a.id=b.id);b.name&&(a.name=b.name);b.type&&(a.type=b.type);"undefined"!=typeof b.value&&(a.value=b.value);if(b.className||b["class"])a.className=b.className||b["class"];if(b.html)if(this.isNode(b.html))a.appendChild(b.html);else if(this.isArray(b.html))for(var d=0,e=b.html.length;d<e;d++)this.isNode(b.html[d])?a.appendChild(b.html[d]):this.isObj(b.html[d])?a.appendChild(this.nodeCreate(b.html[d])):a.innerHTML+=
b.html[d];else this.isObj(b.html)?a.appendChild(this.nodeCreate(b.html)):a.innerHTML=b.html;b.css&&this.nodeCSS(a,b.css);b.attrs&&this.nodeAttrs(a,b.attrs);if(this.isArray(b.event))for(d=0,e=b.event.length;d<e;d++)this.nodeEvent(a,b.event[d],!0);else b.event&&this.nodeEvent(a,b.event,!0);return a},nodeRemove:function(b){this.isNode(b)&&b.parentNode.removeChild(b)},nodeToggleClass:function(b,a,d){if(!this.isNode(b)||!a)return!1;d=d?!0:!1===d?!1:null;var e=new RegExp("(^|\\s+)"+a+"(\\s+|$)"),f=e.test(b.className),
h=!1,m=!1;null===d?(h=!f,m=f):(h=d,m=!0);m&&(b.className=b.className.replace(e," ").replace(/(^\s+)|(\s+$)/g,""));h&&(b.className+=(b.className.length?" ":"")+a)},nodeMetrics:function(b){return this.isNode(b)?(b=b.getBoundingClientRect(),{left:b.left,top:b.top,bottom:b.bottom,right:b.right,width:b.right-b.left,height:b.bottom-b.top}):{}},docMetrics:function(){var b=0,a=0;this.isNu(window.innerWidth)?(b=window.innerWidth,a=window.innerHeight):document.documentElement&&document.documentElement.clientWidth?
(b=document.documentElement.clientWidth,a=document.documentElement.clientHeight):document.body&&document.body.clientWidth&&(b=document.body.clientWidth,a=document.body.clientHeight);return{width:b,height:a}},getNodeById:function(b,a){return(a||document).getElementById(b||"??")||null},getNodeByName:function(b,a,d){var e;return(e=(d||document).getElementsByName(b||"??"))?e[a||0]:null},getNodeByClass:function(b,a,d){var e;return document.getElementsByClassName?(e=(d||document).getElementsByClassName(b||
"??"))?e[a||0]:null:document.querySelectorAll?(e=(d||document).querySelectorAll("."+(b||"??")))?e[a||0]:null:null},getNode:function(a,c,d){var e=null;if(!a||!this.isObjNotEmpty(a))return!1;d=d||document;c=c||0;return e=(e=(e=a.id?this.getNodeById(a.id||"??",d):null)||(a.name?this.getNodeByName(a.name,c,d):null))||(a["class"]||a.className?this.getNodeByClass(a["class"]||a.className,c,d):null)},setWindowsResize:function(a){window.onresize=function(c){a.resize(c)}},docReady:function(a){if(!this.isFct(a))return!1;
var c=document.getElementsByTagName("BODY")[0];c&&"loaded"==c.readyState||c&&"complete"==c.readyState?a():window.addEventListener?window.addEventListener("load",a,!1):window.attachEvent("onload",a)},getJSON:function(a){return a?JSON.parse(a):null},ajax:function(a){a=a||{};var c,d,e=null,f=a.url||null,h=a.post?"POST":"GET",m=!1===a.async||0===a.async?!1:!0,g=a.json?!0:!1,l="function"==typeof a.success?a.success:null,n="function"==typeof a.error?a.error:function(a,b){};if(!a||!f)return!1;if(a.data&&
"object"==typeof a.data&&"undefined"==typeof a.data.length)for(var p in a.data)e=(e?e:"")+(e&&e.length?"&":"")+escape(p)+"="+escape(a.data[p]);!a.post&&e&&(f+=(/\?/i.test(f)?"&":"?")+e);try{c=new XMLHttpRequest}catch(t){try{c=new ActiveXObject("Msxml2.XMLHTTP")}catch(u){try{c=new ActiveXObject("Microsoft.XMLHTTP")}catch(w){return n&&n("Ajax disable"),!1}}}c.onreadystatechange=function(){if(4==c.readyState){d=c.responseText||null;if(404==c.status)n&&n("Error 404 - File not found");else if(200==c.status)if(g){try{d=
JSON.parse(c.responseText)}catch(a){n&&n("Error parsing JSON")}l&&l(d)}else d?/[>\s]+404[\s\.][^<>]+not found/i.test(d)?n&&n("Error 404 - File not found"):l&&l(d):n&&n("Result Empty");return d}};c.open(h,f,m);a.post&&c.setRequestHeader("Content-Type","application/x-www-form-urlencoded");c.send(e)}};a=n.CFG;f=n.TOOLS;t=n.RENDER;u=n.WS;p=n.TTIPS;w=n.EVENTS;l=n.ACTION;x=n.VALID;n.init();f.docReady(function(){n.init({docLoaded:1})})})()})();